name: facial_app_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^1.4.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  flutter_face_api_beta: ^0.0.69
  flutter_barcode_scanner: ^2.0.0
  location: ^4.4.0
 
  geocoding: ^2.0.5
  geocoder2: ^1.4.0
  flutter_geocoder: ^0.2.2-nullsafety
  google_maps_flutter: ^2.2.1
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/images/